name: Terraform Drift Detection

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  
  repository_dispatch:
    types: [manual_trigger]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init
      working-directory: ./Infra

    - name: Terraform Plan
      id: terraform-plan
      run: |
        terraform plan -refresh-only -out=tfplan > plan_output.txt 
        cat plan_output.txt
      working-directory: ./Infra

    - name: Report Drift
      run: |
        # Debug: Show the plan output file
        echo "Plan output:"
        cat plan_output.txt

        line=$(grep -oE '[0-9]+ to add, [0-9]+ to change, [0-9]+ to destroy' plan_output.txt)

        add_count=$(echo $line | awk -F ' ' '{print $1}')
        change_count=$(echo $line | awk -F ' ' '{print $4}')
        destroy_count=$(echo $line | awk -F ' ' '{print $7}')

        echo "Add: $add_count, Change: $change_count, Destroy: $destroy_count"

    
        # # Count the number of changes in the plan output
        # ADDITIONS=$(grep -oP "Plan: \K[0-9]+(?= to add)" plan_output.txt || echo 0)
        # CHANGES=$(grep -oP "Plan: \K[0-9]+(?= to change)" plan_output.txt || echo 0)
        # DESTROY=$(grep -oP "Plan: \K[0-9]+(?= to destroy)" plan_output.txt || echo 0)
    
        # echo "Additions: $ADDITIONS"
        # echo "Changes: $CHANGES"
        # echo "Destroy: $DESTROY"
    
        # Report based on the number of changes
        if [ "$CHANGES" -gt 0 ]; then
          echo "Drift detected: $CHANGES resource(s) to change."
          exit 1
        elif [ "$ADDITIONS" -gt 0 ] || [ "$DESTROY" -gt 0 ]; then
          echo "Resources will be added or destroyed, but no changes detected."
          exit 1
        else
          echo "No drift detected."
        fi
      working-directory: ./Infra
    