name: Terraform Drift Detection

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  
  repository_dispatch:
    types: [manual_trigger]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init
      working-directory: ./Infra

    - name: Terraform Plan
      id: terraform-plan
      run: |
        terraform plan  -out=tfplan > plan_output.txt 
        cat plan_output.txt
      working-directory: ./Infra

    - name: Report Drift
      run: |
        # Check if there are no changes
        if grep -q "No changes. Your infrastructure matches the configuration." plan_output.txt; then
          echo "No drift detected."
          exit 0  # Exit successfully
        fi
    
        # Extract the line with the counts
        line=$(grep -oE '[0-9]+ to add, [0-9]+ to change, [0-9]+ to destroy' plan_output.txt || true)
    
        # Check if the line is not empty
        if [ -n "$line" ]; then
          add_count=$(echo $line | awk -F ' ' '{print $1}')
          change_count=$(echo $line | awk -F ' ' '{print $4}')
          destroy_count=$(echo $line | awk -F ' ' '{print $7}')
    
          echo "Add: $add_count, Change: $change_count, Destroy: $destroy_count"
    
          # Report based on the number of changes
          if [ "$change_count" -gt 0 ]; then 
            echo "Drift detected: $change_count resource(s) to change."
            exit 1
          elif [ "$add_count" -gt 0 ]; then
            echo "Drift detected: $add_count resource(s) to add."
            exit 1
          else
            echo "No drift detected."
          fi
        else
          echo "No drift detected."
        fi
      working-directory: ./Infra
    
    